### ISSUE TITLE
Start Version Controlling Content

### ISSUE THREAD

**Issue by werzl** [werzl/CV#7]
# Description
Need to version control the text content of each section so that the app will just pull the latest version from GitHub.

# Tasks
- [x] Decide on HTML or MD or JSON (Decision = MD and JSON)
- [x] Create a file for each section in this repo.
- [x] Write a method that uses HTTP fetch to get the content for each section.
- [x] Pass section content to the components.
